### PR TITLE
Added PHP 7.3 support - updated Travis CI configuration

### PR DESCRIPTION
**Pull request by michalbundyra**

### CODE REVIEW

**Comment by Ocramius** [comment]
Hmm, should this target `develop` instead? (next minor)

**Comment by michalbundyra** [comment]
@Ocramius 

@weierophinney releases these always in bugfix version when there is no any code changes, that's why I've rebased it and changed target to master.

**Comment by weierophinney** [comment]
As noted on the zend-progressbar PR for 7.3 support, we can target these to the next bugfix, as there are no code or dependency changes; it's simply validating that the component works on the new PHP version.

**Comment by weierophinney** [comment]
Thanks, @webimpress

**Pull request merged**
